/* Allegro datafile object indexes, produced by grabber v4.2.0, Unix */
/* Datafile: /home/hans/projects/worminator/wormdata.dat */
/* Date: Wed Feb  1 19:58:31 2006 */
/* Do not hand edit! */

#define aaaa                             0        /* BMP  */
#define ACCESS_DENIED_SOUND              1        /* SAMP */
#define ALARM_SOUND                      2        /* SAMP */
#define ARAB_WORM_FLY_01                 3        /* BMP  */
#define ARAB_WORM_FLY_02                 4        /* BMP  */
#define ARAB_WORM_FLY_03                 5        /* BMP  */
#define ARAB_WORM_FLY_04                 6        /* BMP  */
#define BFG_FIRE_SOUND                   7        /* SAMP */
#define BFG_PLASMA_BALL_EXPLODE_01       8        /* BMP  */
#define BFG_PLASMA_BALL_EXPLODE_02       9        /* BMP  */
#define BFG_PLASMA_BALL_EXPLODE_03       10       /* BMP  */
#define BFG_PLASMA_BALL_EXPLODE_04       11       /* BMP  */
#define BFG_PLASMA_BALL_EXPLODE_05       12       /* BMP  */
#define BFG_PLASMA_BALL_EXPLODE_06       13       /* BMP  */
#define BFG_PLASMA_BALL_EXPLODE_07       14       /* BMP  */
#define BFG_PLASMA_BALL_EXPLODE_08       15       /* BMP  */
#define BFG_PLASMA_BALL_FLY_01           16       /* BMP  */
#define BFG_PLASMA_BALL_FLY_02           17       /* BMP  */
#define BFG_PLASMA_BALL_FLY_03           18       /* BMP  */
#define BIG_GREEN_SLIME_BLOB_01          19       /* BMP  */
#define BIG_GREEN_SLIME_BLOB_02          20       /* BMP  */
#define BIG_GREEN_SLIME_BLOB_03          21       /* BMP  */
#define BIG_GREEN_SLIME_BLOB_04          22       /* BMP  */
#define BIG_GREEN_SLIME_BLOB_05          23       /* BMP  */
#define BIG_GREEN_SLIME_BLOB_06          24       /* BMP  */
#define BIG_GREEN_SLIME_BLOB_07          25       /* BMP  */
#define BIG_GREEN_SLIME_BLOB_08          26       /* BMP  */
#define BIG_GUN_TURRET_BUSTED            27       /* BMP  */
#define BIG_GUN_TURRET_FIRE_01           28       /* BMP  */
#define BIG_GUN_TURRET_FIRE_02           29       /* BMP  */
#define BIG_GUN_TURRET_FIRE_03           30       /* BMP  */
#define BIG_GUN_TURRET_REST              31       /* BMP  */
#define BIG_NUCLEAR_BOMB                 32       /* BMP  */
#define BLUE_DOOR_01                     33       /* BMP  */
#define BLUE_DOOR_02                     34       /* BMP  */
#define BLUE_KEYCARD                     35       /* BMP  */
#define BLUE_SLIME_DIE_01                36       /* BMP  */
#define BLUE_SLIME_DIE_02                37       /* BMP  */
#define BLUE_SLIME_DIE_03                38       /* BMP  */
#define BLUE_SLIME_DIE_04                39       /* BMP  */
#define BLUE_SLIME_DIE_05                40       /* BMP  */
#define BLUE_SLIME_DIE_06                41       /* BMP  */
#define BLUE_SLIME_DIE_07                42       /* BMP  */
#define BLUE_SLIME_DIE_08                43       /* BMP  */
#define BLUE_SLIME_JUMP_01               44       /* BMP  */
#define BLUE_SLIME_JUMP_02               45       /* BMP  */
#define BLUE_SLIME_JUMP_03               46       /* BMP  */
#define BLUE_SLIME_JUMP_04               47       /* BMP  */
#define BLUE_SLIME_JUMP_05               48       /* BMP  */
#define BLUE_SLIME_JUMP_06               49       /* BMP  */
#define BLUE_SLIME_JUMP_07               50       /* BMP  */
#define BLUE_SLIME_JUMP_08               51       /* BMP  */
#define BLUE_SLIME_JUMP_09               52       /* BMP  */
#define BLUE_SLIME_REST                  53       /* BMP  */
#define BOMB_FALLING_SOUND               54       /* SAMP */
#define BONUS_FLYUP_100_POINT            55       /* BMP  */
#define BONUS_FLYUP_250_POINT            56       /* BMP  */
#define BONUS_FLYUP_500_POINT            57       /* BMP  */
#define BONUS_FLYUP_50_POINT             58       /* BMP  */
#define BORED_FRAME_01                   59       /* BMP  */
#define BORED_FRAME_02                   60       /* BMP  */
#define BORED_FRAME_03                   61       /* BMP  */
#define BORED_FRAME_04                   62       /* BMP  */
#define BORED_FRAME_05                   63       /* BMP  */
#define BORED_FRAME_06                   64       /* BMP  */
#define BOSS_HACK_01                     65       /* BMP  */
#define BOSS_HACK_02                     66       /* BMP  */
#define BOSS_HACK_03                     67       /* BMP  */
#define BOSS_HACK_04                     68       /* BMP  */
#define BOSS_HACK_05                     69       /* BMP  */
#define BOSS_HACK_06                     70       /* BMP  */
#define BOSS_PHASE_01                    71       /* BMP  */
#define BOSS_PHASE_02                    72       /* BMP  */
#define BOSS_PHASE_03                    73       /* BMP  */
#define BOSS_PHASE_04                    74       /* BMP  */
#define BOSS_PHASE_05                    75       /* BMP  */
#define BOSS_PHASE_06                    76       /* BMP  */
#define BOSS_PHASE_07                    77       /* BMP  */
#define BOSS_PHASE_08                    78       /* BMP  */
#define BOSS_SHOOT_01                    79       /* BMP  */
#define BOSS_SHOOT_02                    80       /* BMP  */
#define BOSS_SHOOT_03                    81       /* BMP  */
#define BOSS_SHOOT_04                    82       /* BMP  */
#define BOSS_WALK_01                     83       /* BMP  */
#define BOSS_WALK_02                     84       /* BMP  */
#define BOSS_WALK_03                     85       /* BMP  */
#define BOSS_WALK_04                     86       /* BMP  */
#define BOSS_WALK_05                     87       /* BMP  */
#define BOSS_WALK_06                     88       /* BMP  */
#define BOTTLE_ROCKET_FLY                89       /* BMP  */
#define BOTTLE_ROCKET_FUSE_01            90       /* BMP  */
#define BOTTLE_ROCKET_FUSE_02            91       /* BMP  */
#define BOTTLE_ROCKET_FUSE_03            92       /* BMP  */
#define BOTTLE_ROCKET_FUSE_04            93       /* BMP  */
#define BOTTLE_ROCKET_REST               94       /* BMP  */
#define BOULDER_01                       95       /* BMP  */
#define BOULDER_02                       96       /* BMP  */
#define BOULDER_03                       97       /* BMP  */
#define BOULDER_04                       98       /* BMP  */
#define CAR_01_DEAD                      99       /* BMP  */
#define CAR_01_REST                      100      /* BMP  */
#define CAR_02_DEAD                      101      /* BMP  */
#define CAR_02_REST                      102      /* BMP  */
#define CAR_CRUSH_SOUND                  103      /* SAMP */
#define CHAINSAW_EQUIP_SOUND             104      /* SAMP */
#define CIGARETTE_BUTT_01                105      /* BMP  */
#define CIGARETTE_BUTT_02                106      /* BMP  */
#define COMPANY_LOGO_MOVIE               107      /* NULL */
#define COOL_MODE_COCONUT_MORTAR         108      /* BMP  */
#define COOL_MODE_MUSIC                  109      /* MIDI */
#define COOL_SHIRT_01                    110      /* BMP  */
#define COOL_SHIRT_02                    111      /* BMP  */
#define COOL_SHIRT_03                    112      /* BMP  */
#define COOL_SHIRT_04                    113      /* BMP  */
#define DARK_WORMINATOR_PALLETE          114      /* PAL  */
#define DEATH_ORB                        115      /* BMP  */
#define DECIMATER_DIE_01                 116      /* BMP  */
#define DECIMATER_DIE_02                 117      /* BMP  */
#define DECIMATER_DIE_03                 118      /* BMP  */
#define DECIMATER_DIE_04                 119      /* BMP  */
#define DECIMATER_DIE_05                 120      /* BMP  */
#define DECIMATER_DIE_06                 121      /* BMP  */
#define DECIMATER_DIE_07                 122      /* BMP  */
#define DECIMATER_DIE_08                 123      /* BMP  */
#define DECIMATER_DIE_09                 124      /* BMP  */
#define DECIMATER_DIE_10                 125      /* BMP  */
#define DECIMATER_DIE_11                 126      /* BMP  */
#define DECIMATER_DIE_12                 127      /* BMP  */
#define DECIMATER_DIE_13                 128      /* BMP  */
#define DECIMATER_DIE_14                 129      /* BMP  */
#define DECIMATER_DIE_15                 130      /* BMP  */
#define DECIMATER_DIE_16                 131      /* BMP  */
#define DECIMATER_DIE_17                 132      /* BMP  */
#define DECIMATER_DIE_18                 133      /* BMP  */
#define DECIMATER_DIE_19                 134      /* BMP  */
#define DECIMATER_DIE_20                 135      /* BMP  */
#define DECIMATER_FIRE_01                136      /* BMP  */
#define DECIMATER_FIRE_02                137      /* BMP  */
#define DECIMATER_FIRE_03                138      /* BMP  */
#define DECIMATER_WALK_01                139      /* BMP  */
#define DECIMATER_WALK_02                140      /* BMP  */
#define DECIMATER_WALK_03                141      /* BMP  */
#define DECIMATER_WALK_04                142      /* BMP  */
#define DECIMATER_WALK_05                143      /* BMP  */
#define DECIMATER_WALK_06                144      /* BMP  */
#define DEFAULT_WORMINATOR_FONT          145      /* FONT */
#define DEFAULT_WORMINATOR_PALLETE       146      /* PAL  */
#define DEMO_SIGN                        147      /* BMP  */
#define DOG_BARK_SOUND                   148      /* SAMP */
#define DOOR_OPEN_SOUND                  149      /* SAMP */
#define DULL_THUD_SOUND                  150      /* SAMP */
#define ED_DONE_BUTTON                   151      /* BMP  */
#define ED_DONE_BUTTON_DOWN              152      /* BMP  */
#define ED_EDITOR_SPRITE_CHART           153      /* BMP  */
#define ED_GRAPHICAL_PROPERTIES_TILES    154      /* BMP  */
#define ED_INFO_TILES                    155      /* BMP  */
#define ED_MAIN_EDITOR_CONTROLS_DISPLAY  156      /* BMP  */
#define ED_MAIN_EDITOR_CONTROLS_DOWN     157      /* BMP  */
#define ED_POPUP_DISPLAY_PROPERTIES_WINDOW 158      /* BMP  */
#define ED_POPUP_DISPLAY_PROPERTIES_WINDOW_DOWN 159      /* BMP  */
#define ED_POPUP_SELECT_LAYER_WINDOW     160      /* BMP  */
#define ED_POPUP_SELECT_LAYER_WINDOW_DOWN 161      /* BMP  */
#define ED_POPUP_TOOLS_MENU_WINDOW       162      /* BMP  */
#define ED_POPUP_TOOLS_MENU_WINDOW_DOWN  163      /* BMP  */
#define ED_TILE_BUTTONS                  164      /* BMP  */
#define ED_TILE_BUTTONS_DOWN             165      /* BMP  */
#define EGG_FIRE_SOUND                   166      /* SAMP */
#define EGG_SPLAT_SOUND                  167      /* SAMP */
#define EGG_TAPEWORM_DIE_01              168      /* BMP  */
#define EGG_TAPEWORM_DIE_02              169      /* BMP  */
#define EGG_TAPEWORM_DIE_03              170      /* BMP  */
#define EGG_TAPEWORM_DIE_04              171      /* BMP  */
#define EGG_TAPEWORM_DIE_05              172      /* BMP  */
#define EGG_TAPEWORM_DIE_06              173      /* BMP  */
#define EGG_TAPEWORM_DIE_07              174      /* BMP  */
#define EGG_TAPEWORM_DIE_08              175      /* BMP  */
#define EGG_TAPEWORM_FIRE_01             176      /* BMP  */
#define EGG_TAPEWORM_FIRE_02             177      /* BMP  */
#define EGG_TAPEWORM_FIRE_03             178      /* BMP  */
#define EGG_TAPEWORM_FIRE_04             179      /* BMP  */
#define EGG_TAPEWORM_WALK_01             180      /* BMP  */
#define EGG_TAPEWORM_WALK_02             181      /* BMP  */
#define EGG_TAPEWORM_WALK_03             182      /* BMP  */
#define EGG_TAPEWORM_WALK_04             183      /* BMP  */
#define ENEMY_EGG_FLY                    184      /* BMP  */
#define ENEMY_LASER_BOLT_FLY             185      /* BMP  */
#define ENEMY_MICRO_MISSLES_FLY_01       186      /* BMP  */
#define ENEMY_MICRO_MISSLES_FLY_02       187      /* BMP  */
#define ENEMY_MICRO_MISSLES_FLY_03       188      /* BMP  */
#define ENEMY_MICRO_MISSLES_FLY_04       189      /* BMP  */
#define ENEMY_MISSILE_FLY_01             190      /* BMP  */
#define ENEMY_MISSILE_FLY_02             191      /* BMP  */
#define ENEMY_MISSILE_FLY_03             192      /* BMP  */
#define ENEMY_MISSILE_FLY_04             193      /* BMP  */
#define ENEMY_MORTAR_FLY                 194      /* BMP  */
#define ENEMY_PLASMA_BULLET_FLY          195      /* BMP  */
#define ENEMY_TOXIN_FLY                  196      /* BMP  */
#define FEMALE_SCREAM_01                 197      /* SAMP */
#define FIREWORK_FLY                     198      /* BMP  */
#define FIREWORK_FUSE_01                 199      /* BMP  */
#define FIREWORK_FUSE_02                 200      /* BMP  */
#define FIREWORK_FUSE_03                 201      /* BMP  */
#define FIREWORK_FUSE_04                 202      /* BMP  */
#define FIREWORK_LAUNCH_SOUND            203      /* SAMP */
#define FIREWORK_REST                    204      /* BMP  */
#define FLAME_JET_01                     205      /* BMP  */
#define FLAME_JET_02                     206      /* BMP  */
#define FLAME_JET_03                     207      /* BMP  */
#define FLAME_JET_04                     208      /* BMP  */
#define FLAME_JET_05                     209      /* BMP  */
#define FLAME_JET_06                     210      /* BMP  */
#define FLAME_JET_07                     211      /* BMP  */
#define FLAME_JET_08                     212      /* BMP  */
#define FLAME_JET_09                     213      /* BMP  */
#define FLAME_JET_10                     214      /* BMP  */
#define FLAME_JET_11                     215      /* BMP  */
#define FLAME_JET_12                     216      /* BMP  */
#define FLAME_JET_13                     217      /* BMP  */
#define FLAME_JET_14                     218      /* BMP  */
#define FLAME_JET_15                     219      /* BMP  */
#define FLAME_JET_16                     220      /* BMP  */
#define FLAME_JET_17                     221      /* BMP  */
#define FLAME_JET_18                     222      /* BMP  */
#define FLAME_JET_19                     223      /* BMP  */
#define FLAME_JET_20                     224      /* BMP  */
#define FLAME_JET_21                     225      /* BMP  */
#define FLAME_JET_22                     226      /* BMP  */
#define FLOATING_PLATFORM_01             227      /* BMP  */
#define FLOATING_PLATFORM_02             228      /* BMP  */
#define FLOATING_PLATFORM_03             229      /* BMP  */
#define FLOATING_PLATFORM_04             230      /* BMP  */
#define FLOATING_PLATFORM_05             231      /* BMP  */
#define FLOATING_PLATFORM_06             232      /* BMP  */
#define FLOATING_PLATFORM_07             233      /* BMP  */
#define FLOATING_PLATFORM_08             234      /* BMP  */
#define FLYING_PROBE_FIRE                235      /* BMP  */
#define FLYING_PROBE_FLY                 236      /* BMP  */
#define FOG_WORMINATOR_PALLETE           237      /* PAL  */
#define GIANT_ROBOT_DAMAGED              238      /* BMP  */
#define GIANT_ROBOT_FIRE_01              239      /* BMP  */
#define GIANT_ROBOT_FIRE_02              240      /* BMP  */
#define GIANT_ROBOT_SHRAPNEL_01          241      /* BMP  */
#define GIANT_ROBOT_SHRAPNEL_02          242      /* BMP  */
#define GIANT_ROBOT_SHRAPNEL_03          243      /* BMP  */
#define GIANT_ROBOT_SHRAPNEL_04          244      /* BMP  */
#define GIANT_ROBOT_SHRAPNEL_05          245      /* BMP  */
#define GIANT_ROBOT_SHRAPNEL_06          246      /* BMP  */
#define GIANT_ROBOT_SHRAPNEL_07          247      /* BMP  */
#define GIANT_ROBOT_STAND                248      /* BMP  */
#define GIANT_ROBOT_WALK_01              249      /* BMP  */
#define GIANT_ROBOT_WALK_02              250      /* BMP  */
#define GIANT_ROBOT_WALK_03              251      /* BMP  */
#define GIANT_ROBOT_WALK_04              252      /* BMP  */
#define GIANT_ROBOT_WALK_05              253      /* BMP  */
#define GIANT_ROCKET_FLY_01              254      /* BMP  */
#define GIANT_ROCKET_FLY_02              255      /* BMP  */
#define GIANT_ROCKET_FLY_03              256      /* BMP  */
#define GIANT_ROCKET_FLY_04              257      /* BMP  */
#define GIANT_ROCKET_LAUNCH_01           258      /* BMP  */
#define GIANT_ROCKET_LAUNCH_02           259      /* BMP  */
#define GIANT_ROCKET_LAUNCH_03           260      /* BMP  */
#define GIANT_ROCKET_LAUNCH_04           261      /* BMP  */
#define GIANT_ROCKET_LAUNCH_05           262      /* BMP  */
#define GIANT_ROCKET_REST                263      /* BMP  */
#define GIB_01                           264      /* BMP  */
#define GIB_02                           265      /* BMP  */
#define GIB_03                           266      /* BMP  */
#define GIB_04                           267      /* BMP  */
#define GIB_05                           268      /* BMP  */
#define GIB_06                           269      /* BMP  */
#define GIB_07                           270      /* BMP  */
#define GIB_08                           271      /* BMP  */
#define GIB_09                           272      /* BMP  */
#define GIB_10                           273      /* BMP  */
#define GONG_SOUND                       274      /* SAMP */
#define GREEN_DOOR_01                    275      /* BMP  */
#define GREEN_DOOR_02                    276      /* BMP  */
#define GREEN_DOOR_03_BOTTOM             277      /* BMP  */
#define GREEN_DOOR_03_TOP                278      /* BMP  */
#define GREEN_KEYCARD                    279      /* BMP  */
#define GREY_DOOR_01                     280      /* BMP  */
#define GREY_DOOR_02                     281      /* BMP  */
#define GREY_DOOR_03                     282      /* BMP  */
#define GUMDROP_GIB_01                   283      /* BMP  */
#define GUMDROP_GIB_02                   284      /* BMP  */
#define GUMDROP_MOVE_01                  285      /* BMP  */
#define GUMDROP_MOVE_02                  286      /* BMP  */
#define GUMDROP_MOVE_03                  287      /* BMP  */
#define GUMDROP_MOVE_04                  288      /* BMP  */
#define GUMDROP_MOVE_05                  289      /* BMP  */
#define GUMDROP_MOVE_06                  290      /* BMP  */
#define GUMDROP_MOVE_07                  291      /* BMP  */
#define GUMDROP_MOVE_08                  292      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_01   293      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_02   294      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_03   295      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_04   296      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_05   297      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_06   298      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_07   299      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_08   300      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_09   301      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_10   302      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_11   303      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_12   304      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_DIE_13   305      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_FIRE_01  306      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_FIRE_02  307      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_FIRE_03  308      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_FIRE_04  309      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_FIRE_05  310      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_WALK_01  311      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_WALK_02  312      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_WALK_03  313      /* BMP  */
#define HEAVY_WEAPON_REBEL_WORM_WALK_04  314      /* BMP  */
#define HOLY_MUSIC_SOUND                 315      /* SAMP */
#define INITIATE_SHUTDOWN_SEQUENCE_SOUND 316      /* SAMP */
#define INTRODUCTION_FRAME_01            317      /* BMP  */
#define INTRODUCTION_FRAME_02            318      /* BMP  */
#define ITEM_BIG_TASTY_BALL_O_DIRT       319      /* BMP  */
#define ITEM_BOX_OF_DOUGHNUTS            320      /* BMP  */
#define ITEM_BULLETS_LARGE               321      /* BMP  */
#define ITEM_BULLETS_SMALL               322      /* BMP  */
#define ITEM_CELLS_LARGE                 323      /* BMP  */
#define ITEM_CELLS_SMALL                 324      /* BMP  */
#define ITEM_DIRT_CHIPS                  325      /* BMP  */
#define ITEM_DOUGHNUTS                   326      /* BMP  */
#define ITEM_EXPLOSIVE_SHELLS_LARGE      327      /* BMP  */
#define ITEM_EXPLOSIVE_SHELLS_SMALL      328      /* BMP  */
#define ITEM_GASOLINE_LARGE              329      /* BMP  */
#define ITEM_GASOLINE_SMALL              330      /* BMP  */
#define ITEM_HEALTH_1                    331      /* BMP  */
#define ITEM_HEALTH_10                   332      /* BMP  */
#define ITEM_HEALTH_2                    333      /* BMP  */
#define ITEM_HEALTH_5                    334      /* BMP  */
#define ITEM_LETTER_M                    335      /* BMP  */
#define ITEM_LETTER_O                    336      /* BMP  */
#define ITEM_LETTER_R                    337      /* BMP  */
#define ITEM_LETTER_W                    338      /* BMP  */
#define ITEM_MICRO_NUKE                  339      /* BMP  */
#define ITEM_MINES_LARGE                 340      /* BMP  */
#define ITEM_MINES_SMALL                 341      /* BMP  */
#define ITEM_MINI_MOUNT_N_DO             342      /* BMP  */
#define ITEM_MORTARS_LARGE               343      /* BMP  */
#define ITEM_MORTARS_SMALL               344      /* BMP  */
#define ITEM_MUD_BEER                    345      /* BMP  */
#define ITEM_MUD_ICE_CREAM               346      /* BMP  */
#define ITEM_MUD_PIE                     347      /* BMP  */
#define ITEM_PLASMA_BULLETS_LARGE        348      /* BMP  */
#define ITEM_PLASMA_BULLETS_SMALL        349      /* BMP  */
#define ITEM_PLASMA_LARGE                350      /* BMP  */
#define ITEM_PLASMA_SMALL                351      /* BMP  */
#define ITEM_RAILS_LARGE                 352      /* BMP  */
#define ITEM_RAILS_SMALL                 353      /* BMP  */
#define ITEM_ROCKETS_LARGE               354      /* BMP  */
#define ITEM_ROCKETS_SMALL               355      /* BMP  */
#define ITEM_SHELLS_LARGE                356      /* BMP  */
#define ITEM_SHELLS_SMALL                357      /* BMP  */
#define ITEM_SODA_SIXPACK                358      /* BMP  */
#define ITEM_SPIKESTARS                  359      /* BMP  */
#define ITEM_WALKING_MINES_LARGE         360      /* BMP  */
#define ITEM_WALKING_MINES_SMALL         361      /* BMP  */
#define KEYS                             362      /* BMP  */
#define LARGE_ENEMY_ROCKET_FLY_01        363      /* BMP  */
#define LARGE_ENEMY_ROCKET_FLY_02        364      /* BMP  */
#define LARGE_FAN                        365      /* BMP  */
#define LARGE_NUMBERS_FONT               366      /* FONT */
#define LASER_BOLT_FIRE_SOUND            367      /* SAMP */
#define LASER_GUN_FIRE_SOUND             368      /* SAMP */
#define LASER_REBEL_WORM_DIE_01          369      /* BMP  */
#define LASER_REBEL_WORM_DIE_02          370      /* BMP  */
#define LASER_REBEL_WORM_DIE_03          371      /* BMP  */
#define LASER_REBEL_WORM_DIE_04          372      /* BMP  */
#define LASER_REBEL_WORM_DIE_05          373      /* BMP  */
#define LASER_REBEL_WORM_DIE_06          374      /* BMP  */
#define LASER_REBEL_WORM_DIE_07          375      /* BMP  */
#define LASER_REBEL_WORM_DIE_08          376      /* BMP  */
#define LASER_REBEL_WORM_FIRE_01         377      /* BMP  */
#define LASER_REBEL_WORM_FIRE_02         378      /* BMP  */
#define LASER_REBEL_WORM_FIRE_03         379      /* BMP  */
#define LASER_REBEL_WORM_WALK_01         380      /* BMP  */
#define LASER_REBEL_WORM_WALK_02         381      /* BMP  */
#define LASER_REBEL_WORM_WALK_03         382      /* BMP  */
#define LASER_REBEL_WORM_WALK_04         383      /* BMP  */
#define MAIN_TITLE_SCREEN                384      /* BMP  */
#define MECHANICAL_CRUSHER               385      /* BMP  */
#define MEDIUM_EXPLOSION_01              386      /* BMP  */
#define MEDIUM_EXPLOSION_02              387      /* BMP  */
#define MEDIUM_EXPLOSION_03              388      /* BMP  */
#define MEDIUM_EXPLOSION_04              389      /* BMP  */
#define MEDIUM_EXPLOSION_05              390      /* BMP  */
#define MEDIUM_EXPLOSION_06              391      /* BMP  */
#define MEDIUM_EXPLOSION_07              392      /* BMP  */
#define MEDIUM_EXPLOSION_08              393      /* BMP  */
#define MEDIUM_EXPLOSION_09              394      /* BMP  */
#define MEDIUM_EXPLOSION_10              395      /* BMP  */
#define MEDIUM_FAN                       396      /* BMP  */
#define MICROSLIDE_BUSTED                397      /* BMP  */
#define MICROSLIDE_FIRE_01               398      /* BMP  */
#define MICROSLIDE_FIRE_02               399      /* BMP  */
#define MICROSLIDE_FIRE_03               400      /* BMP  */
#define MICROSLIDE_FIRE_04               401      /* BMP  */
#define MICROSLIDE_FIRE_05               402      /* BMP  */
#define MICROSLIDE_REST                  403      /* BMP  */
#define MINIGUN_FIRE_SOUND               404      /* SAMP */
#define MISSILE_ARM_SOUND                405      /* SAMP */
#define MISSILE_LAUNCH_SOUND             406      /* SAMP */
#define MORTAR_FIRE_SOUND                407      /* SAMP */
#define MORTAR_GUN_TURRET_BUSTED         408      /* BMP  */
#define MORTAR_GUN_TURRET_FIRE_01        409      /* BMP  */
#define MORTAR_GUN_TURRET_FIRE_02        410      /* BMP  */
#define MORTAR_GUN_TURRET_FIRE_03        411      /* BMP  */
#define MORTAR_GUN_TURRET_FIRE_04        412      /* BMP  */
#define MORTAR_GUN_TURRET_FIRE_05        413      /* BMP  */
#define MORTAR_GUN_TURRET_FIRE_06        414      /* BMP  */
#define MORTAR_GUN_TURRET_REST           415      /* BMP  */
#define MOUSE_CURSOR                     416      /* BMP  */
#define MOUSE_CURSOR_01                  417      /* BMP  */
#define MOUSE_CURSOR_02                  418      /* BMP  */
#define MOUSE_CURSOR_03                  419      /* BMP  */
#define MOUSE_CURSOR_04                  420      /* BMP  */
#define MOUSE_CURSOR_05                  421      /* BMP  */
#define MOUSE_CURSOR_06                  422      /* BMP  */
#define MOUSE_CURSOR_07                  423      /* BMP  */
#define MOUSE_CURSOR_08                  424      /* BMP  */
#define MUSHROOM_CLOUD_01                425      /* BMP  */
#define MUSHROOM_CLOUD_02                426      /* BMP  */
#define MUSHROOM_CLOUD_03                427      /* BMP  */
#define MUSHROOM_CLOUD_04                428      /* BMP  */
#define MUSHROOM_CLOUD_05                429      /* BMP  */
#define MUSHROOM_CLOUD_06                430      /* BMP  */
#define MUSHROOM_CLOUD_07                431      /* BMP  */
#define MUSHROOM_CLOUD_08                432      /* BMP  */
#define MUSHROOM_CLOUD_09                433      /* BMP  */
#define MUSHROOM_CLOUD_10                434      /* BMP  */
#define MUSHROOM_CLOUD_11                435      /* BMP  */
#define MUSHROOM_CLOUD_12                436      /* BMP  */
#define MUSHROOM_CLOUD_13                437      /* BMP  */
#define MUSHROOM_CLOUD_14                438      /* BMP  */
#define MUSHROOM_CLOUD_15                439      /* BMP  */
#define MUSHROOM_CLOUD_16                440      /* BMP  */
#define MUSHROOM_CLOUD_17                441      /* BMP  */
#define MUSHROOM_CLOUD_18                442      /* BMP  */
#define MUSHROOM_CLOUD_19                443      /* BMP  */
#define MUSHROOM_CLOUD_20                444      /* BMP  */
#define MUSHROOM_CLOUD_21                445      /* BMP  */
#define MUSHROOM_CLOUD_22                446      /* BMP  */
#define MUSHROOM_CLOUD_23                447      /* BMP  */
#define MUSHROOM_CLOUD_24                448      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_01          449      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_02          450      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_03          451      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_04          452      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_05          453      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_06          454      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_07          455      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_08          456      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_09          457      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_10          458      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_11          459      /* BMP  */
#define NEW_MEDIUM_EXPLOSION_12          460      /* BMP  */
#define NEW_SMALL_EXPLOSION_01           461      /* BMP  */
#define NEW_SMALL_EXPLOSION_02           462      /* BMP  */
#define NEW_SMALL_EXPLOSION_03           463      /* BMP  */
#define NEW_SMALL_EXPLOSION_04           464      /* BMP  */
#define NEW_SMALL_EXPLOSION_05           465      /* BMP  */
#define NEW_SMALL_EXPLOSION_06           466      /* BMP  */
#define NEW_SMALL_EXPLOSION_07           467      /* BMP  */
#define NEW_SMALL_EXPLOSION_08           468      /* BMP  */
#define NEW_SMALL_EXPLOSION_09           469      /* BMP  */
#define NEW_SMALL_EXPLOSION_10           470      /* BMP  */
#define NEW_SMALL_EXPLOSION_11           471      /* BMP  */
#define NEW_SMALL_EXPLOSION_12           472      /* BMP  */
#define NUCLEAR_EXPLOSION_SOUND          473      /* SAMP */
#define NUCLEAR_WORM_WALK_01             474      /* BMP  */
#define NUCLEAR_WORM_WALK_02             475      /* BMP  */
#define PAGE_TURN_SOUND                  476      /* SAMP */
#define PARALLAXING_BACKGROUND_01        477      /* BMP  */
#define PARALLAXING_BACKGROUND_02        478      /* BMP  */
#define PARALLAXING_BACKGROUND_03        479      /* BMP  */
#define PARALLAXING_BACKGROUND_04        480      /* BMP  */
#define PARALLAXING_BACKGROUND_05        481      /* BMP  */
#define PARALLAXING_BACKGROUND_06        482      /* BMP  */
#define PARALLAXING_BACKGROUND_07        483      /* BMP  */
#define PARALLAXING_BACKGROUND_08        484      /* BMP  */
#define PARALLAXING_BACKGROUND_09        485      /* BMP  */
#define PARALLAXING_BACKGROUND_10        486      /* BMP  */
#define PERVERT_MESSAGE                  487      /* BMP  */
#define PICKUP_BFG_SOUND                 488      /* SAMP */
#define PICKUP_ITEM_SOUND                489      /* SAMP */
#define PICKUP_WEAPON_SOUND              490      /* SAMP */
#define PINK_ARROW_SPIN_01               491      /* BMP  */
#define PINK_ARROW_SPIN_02               492      /* BMP  */
#define PINK_ARROW_SPIN_03               493      /* BMP  */
#define PINK_ARROW_SPIN_04               494      /* BMP  */
#define PINK_ARROW_SPIN_05               495      /* BMP  */
#define PINK_ARROW_SPIN_06               496      /* BMP  */
#define PINK_ARROW_SPIN_07               497      /* BMP  */
#define PINK_ARROW_SPIN_08               498      /* BMP  */
#define PINK_ARROW_SPIN_09               499      /* BMP  */
#define PLASMA_BULLET_FIRE_SOUND         500      /* SAMP */
#define PRESS_ANY_KEY_MESSAGE            501      /* BMP  */
#define PUNK_WORM_DIE_01                 502      /* BMP  */
#define PUNK_WORM_DIE_02                 503      /* BMP  */
#define PUNK_WORM_DIE_03                 504      /* BMP  */
#define PUNK_WORM_DIE_04                 505      /* BMP  */
#define PUNK_WORM_DIE_05                 506      /* BMP  */
#define PUNK_WORM_DIE_06                 507      /* BMP  */
#define PUNK_WORM_DIE_07                 508      /* BMP  */
#define PUNK_WORM_DIE_08                 509      /* BMP  */
#define PUNK_WORM_FIRE_01                510      /* BMP  */
#define PUNK_WORM_FIRE_02                511      /* BMP  */
#define PUNK_WORM_FIRE_03                512      /* BMP  */
#define PUNK_WORM_FIRE_04                513      /* BMP  */
#define PUNK_WORM_FIRE_05                514      /* BMP  */
#define PUNK_WORM_WALK_01                515      /* BMP  */
#define PUNK_WORM_WALK_02                516      /* BMP  */
#define PUNK_WORM_WALK_03                517      /* BMP  */
#define PUSHABLE_CRATE                   518      /* BMP  */
#define RED_DOOR_01                      519      /* BMP  */
#define RED_DOOR_02                      520      /* BMP  */
#define RED_DOOR_03_BOTTOM               521      /* BMP  */
#define RED_DOOR_03_TOP                  522      /* BMP  */
#define RED_KEYCARD                      523      /* BMP  */
#define RIFLE_REBEL_WORM_DIE_01          524      /* BMP  */
#define RIFLE_REBEL_WORM_DIE_02          525      /* BMP  */
#define RIFLE_REBEL_WORM_DIE_03          526      /* BMP  */
#define RIFLE_REBEL_WORM_DIE_04          527      /* BMP  */
#define RIFLE_REBEL_WORM_DIE_05          528      /* BMP  */
#define RIFLE_REBEL_WORM_DIE_06          529      /* BMP  */
#define RIFLE_REBEL_WORM_DIE_07          530      /* BMP  */
#define RIFLE_REBEL_WORM_DIE_08          531      /* BMP  */
#define RIFLE_REBEL_WORM_FIRE_01         532      /* BMP  */
#define RIFLE_REBEL_WORM_FIRE_02         533      /* BMP  */
#define RIFLE_REBEL_WORM_FIRE_03         534      /* BMP  */
#define RIFLE_REBEL_WORM_WALK_01         535      /* BMP  */
#define RIFLE_REBEL_WORM_WALK_02         536      /* BMP  */
#define RIFLE_REBEL_WORM_WALK_03         537      /* BMP  */
#define RIFLE_REBEL_WORM_WALK_04         538      /* BMP  */
#define ROBOTIC_DOG_BITE_01              539      /* BMP  */
#define ROBOTIC_DOG_BITE_02              540      /* BMP  */
#define ROBOTIC_DOG_DIE_01               541      /* BMP  */
#define ROBOTIC_DOG_DIE_02               542      /* BMP  */
#define ROBOTIC_DOG_DIE_03               543      /* BMP  */
#define ROBOTIC_DOG_DIE_04               544      /* BMP  */
#define ROBOTIC_DOG_DIE_05               545      /* BMP  */
#define ROBOTIC_DOG_DIE_06               546      /* BMP  */
#define ROBOTIC_DOG_DIE_07               547      /* BMP  */
#define ROBOTIC_DOG_DIE_08               548      /* BMP  */
#define ROBOTIC_DOG_WALK_01              549      /* BMP  */
#define ROBOTIC_DOG_WALK_02              550      /* BMP  */
#define ROBOTIC_DOG_WALK_03              551      /* BMP  */
#define ROBOTIC_DOG_WALK_04              552      /* BMP  */
#define ROCKET_EXPLODE_SOUND             553      /* SAMP */
#define ROCKET_FIRE_SOUND                554      /* SAMP */
#define ROCKET_REBEL_WORM_DIE_01         555      /* BMP  */
#define ROCKET_REBEL_WORM_DIE_02         556      /* BMP  */
#define ROCKET_REBEL_WORM_DIE_03         557      /* BMP  */
#define ROCKET_REBEL_WORM_DIE_04         558      /* BMP  */
#define ROCKET_REBEL_WORM_DIE_05         559      /* BMP  */
#define ROCKET_REBEL_WORM_DIE_06         560      /* BMP  */
#define ROCKET_REBEL_WORM_DIE_07         561      /* BMP  */
#define ROCKET_REBEL_WORM_DIE_08         562      /* BMP  */
#define ROCKET_REBEL_WORM_FIRE_01        563      /* BMP  */
#define ROCKET_REBEL_WORM_FIRE_02        564      /* BMP  */
#define ROCKET_REBEL_WORM_FIRE_03        565      /* BMP  */
#define ROCKET_REBEL_WORM_WALK_01        566      /* BMP  */
#define ROCKET_REBEL_WORM_WALK_02        567      /* BMP  */
#define ROCKET_REBEL_WORM_WALK_03        568      /* BMP  */
#define ROCKET_REBEL_WORM_WALK_04        569      /* BMP  */
#define SHOTGUN_FIRE_SOUND               570      /* SAMP */
#define SHOTGUN_LASER_SIGHT              571      /* BMP  */
#define SHRAPNEL_01                      572      /* BMP  */
#define SHRAPNEL_02                      573      /* BMP  */
#define SHRAPNEL_03                      574      /* BMP  */
#define SHRAPNEL_04                      575      /* BMP  */
#define SHRAPNEL_05                      576      /* BMP  */
#define SHRAPNEL_06                      577      /* BMP  */
#define SHRAPNEL_07                      578      /* BMP  */
#define SHRAPNEL_08                      579      /* BMP  */
#define SKIN_BAKED_TURKEY_DUCK           580      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_01  581      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_02  582      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_03  583      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_04  584      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_05  585      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_06  586      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_07  587      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_08  588      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_09  589      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_10  590      /* BMP  */
#define SKIN_BAKED_TURKEY_FACE_PATCH_DEAD 591      /* BMP  */
#define SKIN_BAKED_TURKEY_JUMP           592      /* BMP  */
#define SKIN_BAKED_TURKEY_STAND          593      /* BMP  */
#define SKIN_BAKED_TURKEY_WALK_01        594      /* BMP  */
#define SKIN_BAKED_TURKEY_WALK_02        595      /* BMP  */
#define SKIN_BAKED_TURKEY_WALK_03        596      /* BMP  */
#define SKIN_BAKED_TURKEY_WALK_04        597      /* BMP  */
#define SKIN_BROWNIE_DUCK                598      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_01       599      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_02       600      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_03       601      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_04       602      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_05       603      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_06       604      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_07       605      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_08       606      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_09       607      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_10       608      /* BMP  */
#define SKIN_BROWNIE_FACE_PATCH_DEAD     609      /* BMP  */
#define SKIN_BROWNIE_JUMP                610      /* BMP  */
#define SKIN_BROWNIE_STAND               611      /* BMP  */
#define SKIN_BROWNIE_WALK_01             612      /* BMP  */
#define SKIN_BROWNIE_WALK_02             613      /* BMP  */
#define SKIN_BROWNIE_WALK_03             614      /* BMP  */
#define SKIN_BROWNIE_WALK_04             615      /* BMP  */
#define SKIN_ENDO_SKELETON_DUCK          616      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_01 617      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_02 618      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_03 619      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_04 620      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_05 621      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_06 622      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_07 623      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_08 624      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_09 625      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_10 626      /* BMP  */
#define SKIN_ENDO_SKELETON_FACE_PATCH_DEAD 627      /* BMP  */
#define SKIN_ENDO_SKELETON_JUMP          628      /* BMP  */
#define SKIN_ENDO_SKELETON_STAND         629      /* BMP  */
#define SKIN_ENDO_SKELETON_WALK_01       630      /* BMP  */
#define SKIN_ENDO_SKELETON_WALK_02       631      /* BMP  */
#define SKIN_ENDO_SKELETON_WALK_03       632      /* BMP  */
#define SKIN_ENDO_SKELETON_WALK_04       633      /* BMP  */
#define SKIN_EVIL_CUBE_DUCK              634      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_01     635      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_02     636      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_03     637      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_04     638      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_05     639      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_06     640      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_07     641      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_08     642      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_09     643      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_10     644      /* BMP  */
#define SKIN_EVIL_CUBE_FACE_PATCH_DEAD   645      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_01           646      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_02           647      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_03           648      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_04           649      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_05           650      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_06           651      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_07           652      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_08           653      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_09           654      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_10           655      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_11           656      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_12           657      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_13           658      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_14           659      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_15           660      /* BMP  */
#define SKIN_EVIL_CUBE_WALK_16           661      /* BMP  */
#define SKIN_HOTDOG_HERO_DUCK            662      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_01   663      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_02   664      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_03   665      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_04   666      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_05   667      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_06   668      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_07   669      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_08   670      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_09   671      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_10   672      /* BMP  */
#define SKIN_HOTDOG_HERO_FACE_PATCH_DEAD 673      /* BMP  */
#define SKIN_HOTDOG_HERO_JUMP            674      /* BMP  */
#define SKIN_HOTDOG_HERO_STAND           675      /* BMP  */
#define SKIN_HOTDOG_HERO_WALK_01         676      /* BMP  */
#define SKIN_HOTDOG_HERO_WALK_02         677      /* BMP  */
#define SKIN_MELON_O_DEATH_DUCK          678      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_01 679      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_02 680      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_03 681      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_04 682      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_05 683      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_06 684      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_07 685      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_08 686      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_09 687      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_10 688      /* BMP  */
#define SKIN_MELON_O_DEATH_FACE_PATCH_DEAD 689      /* BMP  */
#define SKIN_MELON_O_DEATH_JUMP          690      /* BMP  */
#define SKIN_MELON_O_DEATH_STAND         691      /* BMP  */
#define SKIN_MELON_O_DEATH_WALK_01       692      /* BMP  */
#define SKIN_MELON_O_DEATH_WALK_02       693      /* BMP  */
#define SKIN_MELON_O_DEATH_WALK_03       694      /* BMP  */
#define SKIN_MELON_O_DEATH_WALK_04       695      /* BMP  */
#define SKIN_MUMMY_WORM_DUCK             696      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_01    697      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_02    698      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_03    699      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_04    700      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_05    701      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_06    702      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_07    703      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_08    704      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_09    705      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_10    706      /* BMP  */
#define SKIN_MUMMY_WORM_FACE_PATCH_DEAD  707      /* BMP  */
#define SKIN_MUMMY_WORM_JUMP             708      /* BMP  */
#define SKIN_MUMMY_WORM_STAND            709      /* BMP  */
#define SKIN_MUMMY_WORM_WALK_01          710      /* BMP  */
#define SKIN_MUMMY_WORM_WALK_02          711      /* BMP  */
#define SKIN_MUMMY_WORM_WALK_03          712      /* BMP  */
#define SKIN_MUMMY_WORM_WALK_04          713      /* BMP  */
#define SKIN_ORIGINAL_WORMINATOR_FACE_PATCH 714      /* BMP  */
#define SKIN_ORIGINAL_WORMINATOR_STAND   715      /* BMP  */
#define SKIN_TANK_FIRE_PATCH_01          716      /* BMP  */
#define SKIN_TANK_FIRE_PATCH_02          717      /* BMP  */
#define SKIN_TANK_FIRE_PATCH_03          718      /* BMP  */
#define SKIN_TANK_FIRE_PATCH_04          719      /* BMP  */
#define SKIN_TANK_FIRE_PATCH_05          720      /* BMP  */
#define SKIN_TANK_FIRE_PATCH_06          721      /* BMP  */
#define SKIN_TANK_WALK_01                722      /* BMP  */
#define SKIN_TANK_WALK_02                723      /* BMP  */
#define SKIN_TANK_WALK_03                724      /* BMP  */
#define SKIN_TANK_WALK_04                725      /* BMP  */
#define SKIN_TANK_WALK_05                726      /* BMP  */
#define SKIN_TANK_WALK_06                727      /* BMP  */
#define SKIN_TANK_WALK_07                728      /* BMP  */
#define SKIN_TANK_WALK_08                729      /* BMP  */
#define SKIN_TANK_WALK_09                730      /* BMP  */
#define SKIN_TANK_WALK_10                731      /* BMP  */
#define SKIN_TANK_WALK_11                732      /* BMP  */
#define SKIN_TANK_WALK_12                733      /* BMP  */
#define SKIN_TANK_WALK_13                734      /* BMP  */
#define SKIN_TANK_WALK_14                735      /* BMP  */
#define SKIN_TANK_WALK_15                736      /* BMP  */
#define SKIN_TANK_WALK_16                737      /* BMP  */
#define SKIN_THE_ANGEL_DUCK              738      /* BMP  */
#define SKIN_THE_ANGEL_FACE_PATCH_01     739      /* BMP  */
#define SKIN_THE_ANGEL_WALK_01           740      /* BMP  */
#define SKIN_THE_ANGEL_WALK_02           741      /* BMP  */
#define SKIN_THE_ANGEL_WALK_03           742      /* BMP  */
#define SKIN_THE_ANGEL_WALK_04           743      /* BMP  */
#define SKIN_THE_BRAIN_DUCK              744      /* BMP  */
#define SKIN_THE_BRAIN_FACE_PATCH_01     745      /* BMP  */
#define SKIN_THE_BRAIN_JUMP              746      /* BMP  */
#define SKIN_THE_BRAIN_STAND             747      /* BMP  */
#define SKIN_THE_BRAIN_WALK_01           748      /* BMP  */
#define SKIN_THE_BRAIN_WALK_02           749      /* BMP  */
#define SKIN_THE_BRAIN_WALK_03           750      /* BMP  */
#define SKIN_THE_BRAIN_WALK_04           751      /* BMP  */
#define SKIN_THE_DEVIL_DUCK              752      /* BMP  */
#define SKIN_THE_DEVIL_FACE_PATCH_01     753      /* BMP  */
#define SKIN_THE_DEVIL_JUMP              754      /* BMP  */
#define SKIN_THE_DEVIL_STAND             755      /* BMP  */
#define SKIN_THE_DEVIL_WALK_01           756      /* BMP  */
#define SKIN_THE_DEVIL_WALK_02           757      /* BMP  */
#define SKIN_THE_DEVIL_WALK_03           758      /* BMP  */
#define SKIN_THE_DEVIL_WALK_04           759      /* BMP  */
#define SKIN_THE_INVERTEBRATOR_DUCK      760      /* BMP  */
#define SKIN_THE_INVERTEBRATOR_FACE_PATCH_01 761      /* BMP  */
#define SKIN_THE_INVERTEBRATOR_JUMP      762      /* BMP  */
#define SKIN_THE_INVERTEBRATOR_STAND     763      /* BMP  */
#define SKIN_THE_INVERTEBRATOR_WALK_01   764      /* BMP  */
#define SKIN_THE_INVERTEBRATOR_WALK_02   765      /* BMP  */
#define SKIN_THE_INVERTEBRATOR_WALK_03   766      /* BMP  */
#define SKIN_THE_INVERTEBRATOR_WALK_04   767      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_DUCK     768      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_01 769      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_02 770      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_03 771      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_04 772      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_05 773      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_06 774      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_07 775      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_08 776      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_09 777      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_10 778      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_FACE_PATCH_DEAD 779      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_JUMP     780      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_STAND    781      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_WALK_01  782      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_WALK_02  783      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_WALK_03  784      /* BMP  */
#define SKIN_THE_YIPNIK_MIKIMBO_WALK_04  785      /* BMP  */
#define SKIN_VOODOO_BADIE_DUCK           786      /* BMP  */
#define SKIN_VOODOO_BADIE_FACE_PATCH_01  787      /* BMP  */
#define SKIN_VOODOO_BADIE_JUMP           788      /* BMP  */
#define SKIN_VOODOO_BADIE_STAND          789      /* BMP  */
#define SKIN_VOODOO_BADIE_WALK_01        790      /* BMP  */
#define SKIN_VOODOO_BADIE_WALK_02        791      /* BMP  */
#define SKIN_WATERMELON_WONDER_DUCK      792      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_01 793      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_02 794      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_03 795      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_04 796      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_05 797      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_06 798      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_07 799      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_08 800      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_09 801      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_10 802      /* BMP  */
#define SKIN_WATERMELON_WONDER_FACE_PATCH_DEAD 803      /* BMP  */
#define SKIN_WATERMELON_WONDER_JUMP      804      /* BMP  */
#define SKIN_WATERMELON_WONDER_STAND     805      /* BMP  */
#define SKIN_WATERMELON_WONDER_WALK_01   806      /* BMP  */
#define SKIN_WATERMELON_WONDER_WALK_02   807      /* BMP  */
#define SKIN_WATERMELON_WONDER_WALK_03   808      /* BMP  */
#define SKIN_WATERMELON_WONDER_WALK_04   809      /* BMP  */
#define SKIN_YUANTI_DUCK                 810      /* BMP  */
#define SKIN_YUANTI_FACE_PATCH_01        811      /* BMP  */
#define SKIN_YUANTI_JUMP                 812      /* BMP  */
#define SKIN_YUANTI_STAND                813      /* BMP  */
#define SKIN_YUANTI_WALK_01              814      /* BMP  */
#define SKIN_YUANTI_WALK_02              815      /* BMP  */
#define SKIN_YUANTI_WALK_03              816      /* BMP  */
#define SKIN_YUANTI_WALK_04              817      /* BMP  */
#define SMALL_BLUE_SPARK_01              818      /* BMP  */
#define SMALL_BLUE_SPARK_02              819      /* BMP  */
#define SMALL_BLUE_SPARK_03              820      /* BMP  */
#define SMALL_ENEMY_ROCKET_FLY           821      /* BMP  */
#define SMALL_EXPLOSION_01               822      /* BMP  */
#define SMALL_EXPLOSION_02               823      /* BMP  */
#define SMALL_EXPLOSION_03               824      /* BMP  */
#define SMALL_EXPLOSION_04               825      /* BMP  */
#define SMALL_EXPLOSION_05               826      /* BMP  */
#define SMALL_EXPLOSION_06               827      /* BMP  */
#define SMALL_EXPLOSION_07               828      /* BMP  */
#define SMALL_EXPLOSION_08               829      /* BMP  */
#define SMALL_EXPLOSIVE_BARREL           830      /* BMP  */
#define SMALL_EXPLOSIVE_NUCLEAR_CRATE    831      /* BMP  */
#define SMALL_FAN                        832      /* BMP  */
#define SMALL_FLAME_BURN_01              833      /* BMP  */
#define SMALL_FLAME_BURN_02              834      /* BMP  */
#define SMALL_FLAME_BURN_03              835      /* BMP  */
#define SMALL_FLAME_BURN_04              836      /* BMP  */
#define SMALL_FLAME_DIE_01               837      /* BMP  */
#define SMALL_FLAME_DIE_02               838      /* BMP  */
#define SMALL_FLAME_DIE_03               839      /* BMP  */
#define SMALL_FLAME_DIE_04               840      /* BMP  */
#define SMALL_GOLD_SPARK_01              841      /* BMP  */
#define SMALL_GOLD_SPARK_02              842      /* BMP  */
#define SMALL_GOLD_SPARK_03              843      /* BMP  */
#define SMALL_GUN_TURRET_BUSTED          844      /* BMP  */
#define SMALL_GUN_TURRET_FIRE_01         845      /* BMP  */
#define SMALL_GUN_TURRET_FIRE_02         846      /* BMP  */
#define SMALL_GUN_TURRET_FIRE_03         847      /* BMP  */
#define SMALL_GUN_TURRET_REST            848      /* BMP  */
#define SMALL_NUCLEAR_BOMB               849      /* BMP  */
#define SMALL_NUMBERS_FONT               850      /* FONT */
#define SMALL_RED_SPARK_01               851      /* BMP  */
#define SMALL_RED_SPARK_02               852      /* BMP  */
#define SMALL_RED_SPARK_03               853      /* BMP  */
#define SMALL_RUNNER_DIE_01              854      /* BMP  */
#define SMALL_RUNNER_DIE_02              855      /* BMP  */
#define SMALL_RUNNER_DIE_03              856      /* BMP  */
#define SMALL_RUNNER_DIE_04              857      /* BMP  */
#define SMALL_RUNNER_DIE_05              858      /* BMP  */
#define SMALL_RUNNER_DIE_06              859      /* BMP  */
#define SMALL_RUNNER_DIE_07              860      /* BMP  */
#define SMALL_RUNNER_DIE_08              861      /* BMP  */
#define SMALL_RUNNER_RUN_01              862      /* BMP  */
#define SMALL_RUNNER_RUN_02              863      /* BMP  */
#define SMALL_RUNNER_RUN_03              864      /* BMP  */
#define SMALL_RUNNER_RUN_04              865      /* BMP  */
#define SMALL_RUNNER_RUN_05              866      /* BMP  */
#define SMALL_WHITE_SPARK_01             867      /* BMP  */
#define SMALL_WHITE_SPARK_02             868      /* BMP  */
#define SMALL_WHITE_SPARK_03             869      /* BMP  */
#define SPEAR_TAPEWORM_DIE_01            870      /* BMP  */
#define SPEAR_TAPEWORM_DIE_02            871      /* BMP  */
#define SPEAR_TAPEWORM_DIE_03            872      /* BMP  */
#define SPEAR_TAPEWORM_DIE_04            873      /* BMP  */
#define SPEAR_TAPEWORM_DIE_05            874      /* BMP  */
#define SPEAR_TAPEWORM_DIE_06            875      /* BMP  */
#define SPEAR_TAPEWORM_DIE_07            876      /* BMP  */
#define SPEAR_TAPEWORM_DIE_08            877      /* BMP  */
#define SPEAR_TAPEWORM_WALK_01           878      /* BMP  */
#define SPEAR_TAPEWORM_WALK_02           879      /* BMP  */
#define SPEAR_TAPEWORM_WALK_03           880      /* BMP  */
#define SPEAR_TAPEWORM_WALK_04           881      /* BMP  */
#define STOMACH_LEVEL_MESSAGE_01         882      /* BMP  */
#define STOMACH_LEVEL_MESSAGE_02         883      /* BMP  */
#define STOMACH_LEVEL_MESSAGE_03         884      /* BMP  */
#define STOMACH_LEVEL_MESSAGE_04         885      /* BMP  */
#define STOMACH_LEVEL_MESSAGE_05         886      /* BMP  */
#define STOMACH_LEVEL_MESSAGE_06         887      /* BMP  */
#define STOMPING_FOOT_01                 888      /* BMP  */
#define STOMPING_FOOT_02                 889      /* BMP  */
#define SUPER_TURKEY_CAPE_01             890      /* BMP  */
#define SUPER_TURKEY_CAPE_02             891      /* BMP  */
#define SUPER_TURKEY_CAPE_03             892      /* BMP  */
#define SUPER_TURKEY_CAPE_04             893      /* BMP  */
#define SUPER_TURKEY_FRIED_CHICKEN       894      /* BMP  */
#define SUPER_TURKEY_MASHED_POTATOES     895      /* BMP  */
#define TANK_REST                        896      /* BMP  */
#define TANK_SHELL_FLY_01                897      /* BMP  */
#define TANK_SHELL_FLY_02                898      /* BMP  */
#define TANK_SHELL_FLY_03                899      /* BMP  */
#define TANK_SHELL_FLY_04                900      /* BMP  */
#define THUG_WORM_DIE_01                 901      /* BMP  */
#define THUG_WORM_DIE_02                 902      /* BMP  */
#define THUG_WORM_DIE_03                 903      /* BMP  */
#define THUG_WORM_DIE_04                 904      /* BMP  */
#define THUG_WORM_FIRE                   905      /* BMP  */
#define THUG_WORM_WALK_01                906      /* BMP  */
#define THUG_WORM_WALK_02                907      /* BMP  */
#define TILES                            908      /* BMP  */
#define W_1000_MELT_01                   909      /* BMP  */
#define W_1000_MELT_02                   910      /* BMP  */
#define W_1000_MELT_03                   911      /* BMP  */
#define W_1000_MELT_04                   912      /* BMP  */
#define W_1000_MELT_05                   913      /* BMP  */
#define W_1000_MELT_06                   914      /* BMP  */
#define W_1000_MELT_07                   915      /* BMP  */
#define W_1000_MELT_08                   916      /* BMP  */
#define WATER_BUBBLE_01                  917      /* BMP  */
#define WATER_BUBBLE_02                  918      /* BMP  */
#define WATER_BUBBLE_03                  919      /* BMP  */
#define WATER_BUBBLE_04                  920      /* BMP  */
#define WATER_DROP                       921      /* BMP  */
#define WATER_DROP_SPLASH_01             922      /* BMP  */
#define WATER_DROP_SPLASH_02             923      /* BMP  */
#define WATER_DROP_SPLASH_03             924      /* BMP  */
#define WATER_DROP_SPLASH_04             925      /* BMP  */
#define WATER_DROP_SPLASH_05             926      /* BMP  */
#define WATER_DROP_SPLASH_06             927      /* BMP  */
#define WATER_DROP_SPLASH_07             928      /* BMP  */
#define WATER_DROP_SPLASH_08             929      /* BMP  */
#define WATER_GLUB_SOUND                 930      /* SAMP */
#define WATER_SPLASH_01                  931      /* BMP  */
#define WATER_SPLASH_02                  932      /* BMP  */
#define WATER_SPLASH_03                  933      /* BMP  */
#define WATER_SPLASH_04                  934      /* BMP  */
#define WATER_SPLASH_05                  935      /* BMP  */
#define WATER_SPLASH_06                  936      /* BMP  */
#define WATER_SPLASH_07                  937      /* BMP  */
#define WATER_SPLASH_08                  938      /* BMP  */
#define WATER_SPLASH_09                  939      /* BMP  */
#define WATER_SPLASH_10                  940      /* BMP  */
#define WATER_SPLASH_11                  941      /* BMP  */
#define WATER_SPLASH_12                  942      /* BMP  */
#define WATER_SPLASH_13                  943      /* BMP  */
#define WATER_SPLASH_14                  944      /* BMP  */
#define WATER_SPLASH_15                  945      /* BMP  */
#define WATER_SPLASH_16                  946      /* BMP  */
#define WERMAID_SWIM_01                  947      /* BMP  */
#define WERMAID_SWIM_02                  948      /* BMP  */
#define WERMAID_SWIM_03                  949      /* BMP  */
#define WERMAID_SWIM_04                  950      /* BMP  */
#define WERMAID_SWIM_05                  951      /* BMP  */
#define WERMAID_SWIM_06                  952      /* BMP  */
#define WERMAID_SWIM_07                  953      /* BMP  */
#define WERMAID_SWIM_08                  954      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_01      955      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_02      956      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_03      957      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_04      958      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_05      959      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_06      960      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_07      961      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_08      962      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_09      963      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_10      964      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_11      965      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_12      966      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_13      967      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_14      968      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_15      969      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_DIE_16      970      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_REST        971      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_SLIDE_01    972      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_SLIDE_02    973      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_SLIDE_03    974      /* BMP  */
#define WORM_BLONDE_NUDE_ONE_SLIDE_04    975      /* BMP  */
#define WORM_BOY_BLINK                   976      /* BMP  */
#define WORM_BOY_STAND                   977      /* BMP  */
#define WORM_BOY_TALK_01                 978      /* BMP  */
#define WORM_BOY_TALK_02                 979      /* BMP  */
#define WORM_CANNON_BUSTED               980      /* BMP  */
#define WORM_CANNON_FIRE_01              981      /* BMP  */
#define WORM_CANNON_FIRE_02              982      /* BMP  */
#define WORM_CANNON_FIRE_03              983      /* BMP  */
#define WORM_CANNON_FIRE_04              984      /* BMP  */
#define WORM_CANNON_REST                 985      /* BMP  */
#define WORM_CANNON_SUCK_01              986      /* BMP  */
#define WORM_CANNON_SUCK_02              987      /* BMP  */
#define WORM_CANNON_SUCK_03              988      /* BMP  */
#define WORM_CANNON_SUCK_04              989      /* BMP  */
#define WORM_CANNON_SUCK_05              990      /* BMP  */
#define WORM_CANNON_SUCK_06              991      /* BMP  */
#define WORM_CANNON_SUCK_07              992      /* BMP  */
#define WORM_CANNON_SUCK_08              993      /* BMP  */
#define WORM_CANNON_SUCK_09              994      /* BMP  */
#define WORM_CANNON_SUCK_10              995      /* BMP  */
#define WORM_CANNON_SUCK_11              996      /* BMP  */
#define WORM_CANNON_SUCK_12              997      /* BMP  */
#define WORM_CANNON_SUCK_13              998      /* BMP  */
#define WORM_CANNON_SUCK_14              999      /* BMP  */
#define WORM_CANNON_SUCK_15              1000     /* BMP  */
#define WORM_CANNON_SUCK_16              1001     /* BMP  */
#define WORM_COP_DRINK_01                1002     /* BMP  */
#define WORM_COP_DRINK_02                1003     /* BMP  */
#define WORM_COP_DRINK_03                1004     /* BMP  */
#define WORM_COP_STAND                   1005     /* BMP  */
#define WORM_GENTLEMEN_SMOKE_01          1006     /* BMP  */
#define WORM_GENTLEMEN_SMOKE_02          1007     /* BMP  */
#define WORM_GENTLEMEN_SMOKE_03          1008     /* BMP  */
#define WORM_GENTLEMEN_SMOKE_04          1009     /* BMP  */
#define WORM_GIRL_BLINK                  1010     /* BMP  */
#define WORM_GIRL_DIE_01                 1011     /* BMP  */
#define WORM_GIRL_DIE_02                 1012     /* BMP  */
#define WORM_GIRL_DIE_03                 1013     /* BMP  */
#define WORM_GIRL_DIE_04                 1014     /* BMP  */
#define WORM_GIRL_DIE_05                 1015     /* BMP  */
#define WORM_GIRL_DIE_06                 1016     /* BMP  */
#define WORM_GIRL_DIE_07                 1017     /* BMP  */
#define WORM_GIRL_DIE_08                 1018     /* BMP  */
#define WORM_GIRL_HEAD                   1019     /* BMP  */
#define WORM_GIRL_STAND                  1020     /* BMP  */
#define WORM_GIRL_TALK_01                1021     /* BMP  */
#define WORM_GIRL_TALK_02                1022     /* BMP  */
#define WORM_STRIPPER_ONE_BOUNCE_01      1023     /* BMP  */
#define WORM_STRIPPER_ONE_BOUNCE_02      1024     /* BMP  */
#define WORM_STRIPPER_ONE_BOUNCE_03      1025     /* BMP  */
#define WORM_STRIPPER_ONE_BOUNCE_04      1026     /* BMP  */
#define WORM_STRIPPER_ONE_BOUNCE_05      1027     /* BMP  */
#define WORM_STRIPPER_ONE_BOUNCE_06      1028     /* BMP  */
#define WORM_STRIPPER_ONE_BOUNCE_07      1029     /* BMP  */
#define WORM_STRIPPER_ONE_BOUNCE_08      1030     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_01         1031     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_02         1032     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_03         1033     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_04         1034     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_05         1035     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_06         1036     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_07         1037     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_08         1038     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_09         1039     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_10         1040     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_11         1041     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_12         1042     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_13         1043     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_14         1044     /* BMP  */
#define WORM_STRIPPER_ONE_DIE_15         1045     /* BMP  */
#define WORM_STRIPPER_ONE_REST           1046     /* BMP  */
#define WORMCODE                         1047     /* BMP  */
#define WORMINATOR_BFG                   1048     /* BMP  */
#define WORMINATOR_BFG_FIRE_01           1049     /* BMP  */
#define WORMINATOR_BFG_FIRE_02           1050     /* BMP  */
#define WORMINATOR_BFG_FIRE_03           1051     /* BMP  */
#define WORMINATOR_BFG_FIRE_04           1052     /* BMP  */
#define WORMINATOR_BFG_FIRE_05           1053     /* BMP  */
#define WORMINATOR_BFG_FIRE_06           1054     /* BMP  */
#define WORMINATOR_BULLET_FLY            1055     /* BMP  */
#define WORMINATOR_CHAINSAW              1056     /* BMP  */
#define WORMINATOR_CHAINSAW_FIRE_01      1057     /* BMP  */
#define WORMINATOR_CHAINSAW_FIRE_02      1058     /* BMP  */
#define WORMINATOR_CHAINSAW_FIRE_03      1059     /* BMP  */
#define WORMINATOR_DIE_A_01              1060     /* BMP  */
#define WORMINATOR_DIE_A_02              1061     /* BMP  */
#define WORMINATOR_DIE_A_03              1062     /* BMP  */
#define WORMINATOR_DIE_A_04              1063     /* BMP  */
#define WORMINATOR_DIE_A_05              1064     /* BMP  */
#define WORMINATOR_DIE_A_06              1065     /* BMP  */
#define WORMINATOR_DIE_A_07              1066     /* BMP  */
#define WORMINATOR_DIE_A_08              1067     /* BMP  */
#define WORMINATOR_DIE_A_09              1068     /* BMP  */
#define WORMINATOR_DIE_A_10              1069     /* BMP  */
#define WORMINATOR_DIE_A_11              1070     /* BMP  */
#define WORMINATOR_DIE_A_12              1071     /* BMP  */
#define WORMINATOR_DUAL_ROCKET_LAUNCHER  1072     /* BMP  */
#define WORMINATOR_DUAL_ROCKET_LAUNCHER_FIRE_01 1073     /* BMP  */
#define WORMINATOR_DUAL_ROCKET_LAUNCHER_FIRE_02 1074     /* BMP  */
#define WORMINATOR_DUAL_ROCKET_LAUNCHER_FIRE_03 1075     /* BMP  */
#define WORMINATOR_DUAL_ROCKET_LAUNCHER_FIRE_04 1076     /* BMP  */
#define WORMINATOR_DUCK_SET_01           1077     /* BMP  */
#define WORMINATOR_DUCK_SET_02           1078     /* BMP  */
#define WORMINATOR_DUCK_SET_03           1079     /* BMP  */
#define WORMINATOR_DUCK_SET_04           1080     /* BMP  */
#define WORMINATOR_FACE_PATCH_01         1081     /* BMP  */
#define WORMINATOR_FACE_PATCH_02         1082     /* BMP  */
#define WORMINATOR_FACE_PATCH_03         1083     /* BMP  */
#define WORMINATOR_FACE_PATCH_04         1084     /* BMP  */
#define WORMINATOR_FACE_PATCH_05         1085     /* BMP  */
#define WORMINATOR_FACE_PATCH_06         1086     /* BMP  */
#define WORMINATOR_FACE_PATCH_07         1087     /* BMP  */
#define WORMINATOR_FACE_PATCH_08         1088     /* BMP  */
#define WORMINATOR_FACE_PATCH_09         1089     /* BMP  */
#define WORMINATOR_FACE_PATCH_10         1090     /* BMP  */
#define WORMINATOR_FACE_PATCH_DEAD       1091     /* BMP  */
#define WORMINATOR_FLAMETHROWER          1092     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_01  1093     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_02  1094     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_03  1095     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_04  1096     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_05  1097     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_06  1098     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_07  1099     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_08  1100     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_09  1101     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_10  1102     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_11  1103     /* BMP  */
#define WORMINATOR_FLAMETHROWER_FIRE_12  1104     /* BMP  */
#define WORMINATOR_HUD                   1105     /* BMP  */
#define WORMINATOR_HUD_ITEMS_PATCH       1106     /* BMP  */
#define WORMINATOR_HUD_ITEMS_PATCH_EMPTY 1107     /* BMP  */
#define WORMINATOR_HUD_ITEMS_PATCH_EMPTY_GLOW 1108     /* BMP  */
#define WORMINATOR_HUD_ITEMS_PATCH_GLOW  1109     /* BMP  */
#define WORMINATOR_HUD_OLD               1110     /* BMP  */
#define WORMINATOR_JUMP_SET_01           1111     /* BMP  */
#define WORMINATOR_JUMP_SET_02           1112     /* BMP  */
#define WORMINATOR_JUMP_SET_03           1113     /* BMP  */
#define WORMINATOR_JUMP_SET_04           1114     /* BMP  */
#define WORMINATOR_LASER_GUN             1115     /* BMP  */
#define WORMINATOR_LASER_GUN_FIRE_01     1116     /* BMP  */
#define WORMINATOR_LASER_GUN_FIRE_02     1117     /* BMP  */
#define WORMINATOR_LOGO_MOVIE            1118     /* NULL */
#define WORMINATOR_MICRO_NUKE_FLY        1119     /* BMP  */
#define WORMINATOR_MINE_ARM              1120     /* BMP  */
#define WORMINATOR_MINE_FLASH            1121     /* BMP  */
#define WORMINATOR_MINE_LAYER            1122     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_01     1123     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_02     1124     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_03     1125     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_04     1126     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_05     1127     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_06     1128     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_07     1129     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_08     1130     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_09     1131     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_10     1132     /* BMP  */
#define WORMINATOR_MINE_LAYER_LAY_11     1133     /* BMP  */
#define WORMINATOR_MINE_LAYER_WALKING_MINE_MASK 1134     /* BMP  */
#define WORMINATOR_MINE_REST             1135     /* BMP  */
#define WORMINATOR_MINIGUN               1136     /* BMP  */
#define WORMINATOR_MINIGUN_FIRE_01       1137     /* BMP  */
#define WORMINATOR_MINIGUN_FIRE_02       1138     /* BMP  */
#define WORMINATOR_MINIGUN_FIRE_03       1139     /* BMP  */
#define WORMINATOR_MINIGUN_PLASMA_BULLET_MASK 1140     /* BMP  */
#define WORMINATOR_MINIGUN_TURN          1141     /* BMP  */
#define WORMINATOR_MORTAR_CANNON         1142     /* BMP  */
#define WORMINATOR_MORTAR_CANNON_FIRE_01 1143     /* BMP  */
#define WORMINATOR_MORTAR_CANNON_FIRE_02 1144     /* BMP  */
#define WORMINATOR_MORTAR_CANNON_FIRE_03 1145     /* BMP  */
#define WORMINATOR_MORTAR_FLY            1146     /* BMP  */
#define WORMINATOR_MUSIC_01              1147     /* MIDI */
#define WORMINATOR_MUSIC_02              1148     /* MIDI */
#define WORMINATOR_MUSIC_03              1149     /* MIDI */
#define WORMINATOR_MUSIC_04              1150     /* MIDI */
#define WORMINATOR_MUSIC_05              1151     /* MIDI */
#define WORMINATOR_MUSIC_06              1152     /* MIDI */
#define WORMINATOR_MUSIC_07              1153     /* MIDI */
#define WORMINATOR_MUSIC_08              1154     /* MIDI */
#define WORMINATOR_MUSIC_09              1155     /* MIDI */
#define WORMINATOR_MUSIC_10              1156     /* MIDI */
#define WORMINATOR_PLASMA_BULLET_FLY     1157     /* BMP  */
#define WORMINATOR_RAILGUN               1158     /* BMP  */
#define WORMINATOR_RAILGUN_FIRE_01       1159     /* BMP  */
#define WORMINATOR_RAILGUN_FIRE_02       1160     /* BMP  */
#define WORMINATOR_RAILGUN_FIRE_03       1161     /* BMP  */
#define WORMINATOR_ROCKET_FLY            1162     /* BMP  */
#define WORMINATOR_ROCKET_LAUNCHER       1163     /* BMP  */
#define WORMINATOR_ROCKET_LAUNCHER_FIRE_01 1164     /* BMP  */
#define WORMINATOR_ROCKET_LAUNCHER_FIRE_02 1165     /* BMP  */
#define WORMINATOR_ROCKET_LAUNCHER_FIRE_03 1166     /* BMP  */
#define WORMINATOR_ROCKET_LAUNCHER_MICRO_NUKE_MASK 1167     /* BMP  */
#define WORMINATOR_SHOTGUN               1168     /* BMP  */
#define WORMINATOR_SHOTGUN_COCK_01       1169     /* BMP  */
#define WORMINATOR_SHOTGUN_COCK_02       1170     /* BMP  */
#define WORMINATOR_SHOTGUN_COCK_03       1171     /* BMP  */
#define WORMINATOR_SHOTGUN_EXPLOSIVE_SHELL_MASK 1172     /* BMP  */
#define WORMINATOR_SHOTGUN_FIRE_01       1173     /* BMP  */
#define WORMINATOR_SHOTGUN_FIRE_02       1174     /* BMP  */
#define WORMINATOR_SHOTGUN_FIRE_03       1175     /* BMP  */
#define WORMINATOR_SPIKESTAR_BLUE_FLY    1176     /* BMP  */
#define WORMINATOR_SPIKESTAR_RED_FLY     1177     /* BMP  */
#define WORMINATOR_SPIKESTAR_YELLOW_FLY  1178     /* BMP  */
#define WORMINATOR_STAND_SET_01          1179     /* BMP  */
#define WORMINATOR_STAND_SET_02          1180     /* BMP  */
#define WORMINATOR_STAND_SET_03          1181     /* BMP  */
#define WORMINATOR_STAND_SET_04          1182     /* BMP  */
#define WORMINATOR_STARDUSTER            1183     /* BMP  */
#define WORMINATOR_STARDUSTER_FIRE_01    1184     /* BMP  */
#define WORMINATOR_STARDUSTER_FIRE_02    1185     /* BMP  */
#define WORMINATOR_STARDUSTER_FIRE_03    1186     /* BMP  */
#define WORMINATOR_STARDUSTER_FIRE_04    1187     /* BMP  */
#define WORMINATOR_STARDUSTER_FIRE_05    1188     /* BMP  */
#define WORMINATOR_SWIM_01_SET_01        1189     /* BMP  */
#define WORMINATOR_SWIM_01_SET_02        1190     /* BMP  */
#define WORMINATOR_SWIM_01_SET_03        1191     /* BMP  */
#define WORMINATOR_SWIM_01_SET_04        1192     /* BMP  */
#define WORMINATOR_SWIM_02_SET_01        1193     /* BMP  */
#define WORMINATOR_SWIM_02_SET_02        1194     /* BMP  */
#define WORMINATOR_SWIM_02_SET_03        1195     /* BMP  */
#define WORMINATOR_SWIM_02_SET_04        1196     /* BMP  */
#define WORMINATOR_SWIM_03_SET_01        1197     /* BMP  */
#define WORMINATOR_SWIM_03_SET_02        1198     /* BMP  */
#define WORMINATOR_SWIM_03_SET_03        1199     /* BMP  */
#define WORMINATOR_SWIM_03_SET_04        1200     /* BMP  */
#define WORMINATOR_SWIM_04_SET_01        1201     /* BMP  */
#define WORMINATOR_SWIM_04_SET_02        1202     /* BMP  */
#define WORMINATOR_SWIM_04_SET_03        1203     /* BMP  */
#define WORMINATOR_SWIM_04_SET_04        1204     /* BMP  */
#define WORMINATOR_WALK_01_SET_01        1205     /* BMP  */
#define WORMINATOR_WALK_01_SET_02        1206     /* BMP  */
#define WORMINATOR_WALK_01_SET_03        1207     /* BMP  */
#define WORMINATOR_WALK_01_SET_04        1208     /* BMP  */
#define WORMINATOR_WALK_02_SET_01        1209     /* BMP  */
#define WORMINATOR_WALK_02_SET_02        1210     /* BMP  */
#define WORMINATOR_WALK_02_SET_03        1211     /* BMP  */
#define WORMINATOR_WALK_02_SET_04        1212     /* BMP  */
#define WORMINATOR_WALK_03_SET_01        1213     /* BMP  */
#define WORMINATOR_WALK_03_SET_02        1214     /* BMP  */
#define WORMINATOR_WALK_03_SET_03        1215     /* BMP  */
#define WORMINATOR_WALK_03_SET_04        1216     /* BMP  */
#define WORMINATOR_WALK_04_SET_01        1217     /* BMP  */
#define WORMINATOR_WALK_04_SET_02        1218     /* BMP  */
#define WORMINATOR_WALK_04_SET_03        1219     /* BMP  */
#define WORMINATOR_WALK_04_SET_04        1220     /* BMP  */
#define WORMINATOR_WALKING_MINE_ARM      1221     /* BMP  */
#define WORMINATOR_WALKING_MINE_WALK_01  1222     /* BMP  */
#define WORMINATOR_WALKING_MINE_WALK_02  1223     /* BMP  */
#define WORMY_ABOUT_HELP                 1224     /* BMP  */
#define WORMY_CHEATS_MENU                1225     /* BMP  */
#define WORMY_CONTROLS_HELP              1226     /* BMP  */
#define WORMY_CONTROLS_MENU_1            1227     /* BMP  */
#define WORMY_CONTROLS_MENU_2            1228     /* BMP  */
#define WORMY_CONTROLS_MENU_3            1229     /* BMP  */
#define WORMY_CRAPATANA_BRIEFING         1230     /* BMP  */
#define WORMY_CREDITS_HELP               1231     /* BMP  */
#define WORMY_CUTSCENE_01                1232     /* BMP  */
#define WORMY_CUTSCENE_02                1233     /* BMP  */
#define WORMY_CUTSCENE_03                1234     /* BMP  */
#define WORMY_CUTSCENE_04                1235     /* BMP  */
#define WORMY_CUTSCENE_05                1236     /* BMP  */
#define WORMY_CUTSCENE_06                1237     /* BMP  */
#define WORMY_DUMMY_BOX                  1238     /* BMP  */
#define WORMY_DUMMY_BOX_EXIT_GAME_PATCH  1239     /* BMP  */
#define WORMY_DUMMY_BOX_LOAD_GAME_PATCH  1240     /* BMP  */
#define WORMY_DUMMY_BOX_NEW_GAME_PATCH   1241     /* BMP  */
#define WORMY_DUMMY_BOX_SAVE_GAME_PATCH  1242     /* BMP  */
#define WORMY_ENDING_MESSAGE             1243     /* BMP  */
#define WORMY_ENEMIES_HELP               1244     /* BMP  */
#define WORMY_FAMOUS_LAST_WORDS          1245     /* BMP  */
#define WORMY_FINALE_MOVIE               1246     /* NULL */
#define WORMY_FINALE_PAGE_01             1247     /* BMP  */
#define WORMY_FINALE_PAGE_01_PALLETE     1248     /* PAL  */
#define WORMY_FINALE_PAGE_02             1249     /* BMP  */
#define WORMY_FINALE_PAGE_02_PALLETE     1250     /* PAL  */
#define WORMY_FINALE_PAGE_03             1251     /* BMP  */
#define WORMY_FINALE_PAGE_03_PALLETE     1252     /* PAL  */
#define WORMY_FINALE_PAGE_04             1253     /* BMP  */
#define WORMY_FINALE_PAGE_04_PALLETE     1254     /* PAL  */
#define WORMY_GAME_MENU                  1255     /* BMP  */
#define WORMY_GENERAL_HELP               1256     /* BMP  */
#define WORMY_GOODBYE_MESSAGE            1257     /* BMP  */
#define WORMY_HELP_MENU                  1258     /* BMP  */
#define WORMY_HIGH_SCORE_INPUT_BOX       1259     /* BMP  */
#define WORMY_HIGH_SCORES                1260     /* BMP  */
#define WORMY_LEVEL_01_BRIEFING          1261     /* BMP  */
#define WORMY_LEVEL_02_BRIEFING          1262     /* BMP  */
#define WORMY_LEVEL_03_BRIEFING          1263     /* BMP  */
#define WORMY_LEVEL_04_BRIEFING          1264     /* BMP  */
#define WORMY_LEVEL_05_BRIEFING          1265     /* BMP  */
#define WORMY_LEVEL_06_BRIEFING          1266     /* BMP  */
#define WORMY_LEVEL_07_BRIEFING          1267     /* BMP  */
#define WORMY_LEVEL_08_BRIEFING          1268     /* BMP  */
#define WORMY_LEVEL_09_BRIEFING          1269     /* BMP  */
#define WORMY_LEVEL_10_BRIEFING          1270     /* BMP  */
#define WORMY_LEVEL_11_BRIEFING          1271     /* BMP  */
#define WORMY_LEVEL_12_BRIEFING          1272     /* BMP  */
#define WORMY_LEVEL_13_BRIEFING          1273     /* BMP  */
#define WORMY_LEVEL_14_BRIEFING          1274     /* BMP  */
#define WORMY_LEVEL_15_BRIEFING          1275     /* BMP  */
#define WORMY_LEVEL_16_BRIEFING          1276     /* BMP  */
#define WORMY_LEVEL_17_BRIEFING          1277     /* BMP  */
#define WORMY_LEVEL_18_BRIEFING          1278     /* BMP  */
#define WORMY_LEVEL_19_BRIEFING          1279     /* BMP  */
#define WORMY_MENU_BAR                   1280     /* BMP  */
#define WORMY_MENU_BAR_SHOW_CHEATS       1281     /* BMP  */
#define WORMY_NEW_GAME_SUBMENU           1282     /* BMP  */
#define WORMY_OPTIONS_MENU               1283     /* BMP  */
#define WORMY_OPTIONS_MENU_DIFFICULTY_DROPDOWN 1284     /* BMP  */
#define WORMY_OPTIONS_MENU_GAME_SPEED_DROPDOWN 1285     /* BMP  */
#define WORMY_OPTIONS_MENU_GLOW_PATCH    1286     /* BMP  */
#define WORMY_OPTIONS_MENU_RESOLUTION_DROPDOWN 1287     /* BMP  */
#define WORMY_PRESS_ANY_KEY_BOX          1288     /* BMP  */
#define WORMY_SCROLLING_FINALE           1289     /* BMP  */
#define WORMY_SKINS_MENU                 1290     /* BMP  */
#define WORMY_STORY_PAGE_01              1291     /* BMP  */
#define WORMY_STORY_PAGE_02              1292     /* BMP  */
#define WORMY_STORY_PAGE_03              1293     /* BMP  */
#define WORMY_STORY_PAGE_04              1294     /* BMP  */
#define WORMY_STORY_RECAP_PAGE_01        1295     /* BMP  */
#define WORMY_STORY_RECAP_PAGE_02        1296     /* BMP  */
#define WORMY_THE_END_OF_IT_ALL          1297     /* BMP  */
#define WORMY_THE_END_OF_IT_ALL_PALLETE  1298     /* PAL  */
#define WORMY_WEAPONS_HELP               1299     /* BMP  */
#define ZZ_ITEM_LIFE_ESSENCE_01          1300     /* BMP  */
#define ZZ_ITEM_LIFE_ESSENCE_02          1301     /* BMP  */
#define ZZ_ITEM_LIFE_ESSENCE_03          1302     /* BMP  */
#define ZZ_ITEM_LIFE_ESSENCE_04          1303     /* BMP  */

